# Generated by Django 5.1.1 on 2024-11-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("ML", "Sofa"),
                    ("PK", "Phòng khách"),
                    ("BD", "Phòng ngủ"),
                    ("TG", "Tủ giày"),
                    ("PA", "Phòng ăn"),
                    ("TV", "Tủ tivi"),
                    ("KS", "Kệ sách"),
                ],
                max_length=100,
            ),
        ),
    ]
