# Generated by Django 5.1.1 on 2024-11-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(max_length=10000, upload_to="product"),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(to="app.category"),
        ),
    ]
