# Generated by Django 5.1.1 on 2024-11-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_category_remove_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("ML", "Sofa"),
                    ("CZ", "Phòng khách"),
                    ("BD", "Phòng ngủ"),
                    ("TB", "Tủ bếp"),
                    ("PA", "Phòng ăn"),
                    ("BA", "Bàn ăn"),
                    ("TV", "Tủ tivi"),
                    ("KS", "Kệ sách"),
                ],
                max_length=100,
            ),
        ),
    ]
