# Generated by Django 5.1.1 on 2024-11-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_category_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("ML", "Sofa"),
                    ("CZ", "Phòng khách"),
                    ("BD", "Phòng ngủ"),
                    ("TB", "Tủ Bếp"),
                    ("PA", "Phòng ăn"),
                    ("BA", "Bàn ăn"),
                    ("TV", "Tủ tivi"),
                    ("KS", "Kệ sách"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
